import { SSISComponent, Connection } from './types';

export interface Template {
    id: string;
    name: string;
    description: string;
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
    components: SSISComponent[];
    connections: Connection[];
}

export const TEMPLATES: Template[] = [
    {
        id: 'basic-etl',
        name: 'Basic ETL: Database to CSV',
        description: 'Extract data from SQL Server, transform with Data Conversion, load to Flat File',
        difficulty: 'Beginner',
        components: [
            {
                id: 'template1-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'OLE DB Source',
                icon: '🗄️',
                description: 'Reads data from SQL Server, Oracle, or OLE DB compliant databases.',
                useCases: ['Reading from SQL tables', 'Executing SQL queries'],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn1'],
                hasError: false
            },
            {
                id: 'template1-transform',
                type: 'transformation',
                category: 'DataConversion',
                name: 'Data Conversion',
                icon: '🔄',
                description: 'Converts data from one type to another.',
                useCases: ['Fixing type mismatches', 'Converting text to numbers'],
                dataType: 'structured',
                position: { x: 400, y: 200 },
                inputs: ['conn1'],
                outputs: ['conn2'],
                hasError: false
            },
            {
                id: 'template1-dest',
                type: 'destination',
                category: 'FlatFileDestination',
                name: 'Flat File Destination',
                icon: '📄',
                description: 'Writes data to a text file (CSV, TXT).',
                useCases: ['Generating reports', 'Exporting for other systems'],
                dataType: 'text',
                position: { x: 700, y: 200 },
                inputs: ['conn2'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            {
                id: 'conn1',
                source: 'template1-source',
                target: 'template1-transform',
                isValid: true
            },
            {
                id: 'conn2',
                source: 'template1-transform',
                target: 'template1-dest',
                isValid: true
            }
        ]
    },
    {
        id: 'merge-join',
        name: 'Merge Two Sorted Datasets',
        description: 'Demonstrates Merge Join with two sorted inputs',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template2-source1',
                type: 'source',
                category: 'OLEDBSource',
                name: 'OLE DB Source 1',
                icon: '🗄️',
                description: 'First data source',
                useCases: [],
                dataType: 'structured',
                position: { x: 50, y: 100 },
                inputs: [],
                outputs: ['conn3'],
                hasError: false
            },
            {
                id: 'template2-sort1',
                type: 'transformation',
                category: 'Sort',
                name: 'Sort 1',
                icon: '⬆️',
                description: 'Sorts input data by one or more columns.',
                useCases: ['Preparing for Merge Join', 'Ordering for reports'],
                dataType: 'structured',
                position: { x: 250, y: 100 },
                inputs: ['conn3'],
                outputs: ['conn5'],
                hasError: false,
                isSorted: true
            },
            {
                id: 'template2-source2',
                type: 'source',
                category: 'OLEDBSource',
                name: 'OLE DB Source 2',
                icon: '🗄️',
                description: 'Second data source',
                useCases: [],
                dataType: 'structured',
                position: { x: 50, y: 300 },
                inputs: [],
                outputs: ['conn4'],
                hasError: false
            },
            {
                id: 'template2-sort2',
                type: 'transformation',
                category: 'Sort',
                name: 'Sort 2',
                icon: '⬆️',
                description: 'Sorts input data by one or more columns.',
                useCases: [],
                dataType: 'structured',
                position: { x: 250, y: 300 },
                inputs: ['conn4'],
                outputs: ['conn6'],
                hasError: false,
                isSorted: true
            },
            {
                id: 'template2-merge',
                type: 'transformation',
                category: 'MergeJoin',
                name: 'Merge Join',
                icon: '🔗',
                description: 'Merges two sorted datasets using FULL, LEFT, or INNER join.',
                useCases: ['Joining large sorted datasets', 'Combining historical data'],
                dataType: 'structured',
                position: { x: 500, y: 200 },
                inputs: ['conn5', 'conn6'],
                outputs: ['conn7'],
                hasError: false
            },
            {
                id: 'template2-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'OLE DB Destination',
                icon: '💾',
                description: 'Writes data to a SQL Server or OLE DB database.',
                useCases: ['Loading data warehouse', 'Updating records'],
                dataType: 'structured',
                position: { x: 750, y: 200 },
                inputs: ['conn7'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn3', source: 'template2-source1', target: 'template2-sort1', isValid: true },
            { id: 'conn4', source: 'template2-source2', target: 'template2-sort2', isValid: true },
            { id: 'conn5', source: 'template2-sort1', target: 'template2-merge', isValid: true },
            { id: 'conn6', source: 'template2-sort2', target: 'template2-merge', isValid: true },
            { id: 'conn7', source: 'template2-merge', target: 'template2-dest', isValid: true }
        ]
    },
    {
        id: 'conditional-split',
        name: 'Conditional Routing',
        description: 'Route data to different destinations based on conditions',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template3-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'OLE DB Source',
                icon: '🗄️',
                description: 'Source data',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn8'],
                hasError: false
            },
            {
                id: 'template3-split',
                type: 'transformation',
                category: 'ConditionalSplit',
                name: 'Conditional Split',
                icon: '🔀',
                description: 'Routes rows to different outputs based on conditions.',
                useCases: ['Separating bad data', 'Routing by region'],
                dataType: 'structured',
                position: { x: 350, y: 200 },
                inputs: ['conn8'],
                outputs: ['conn9', 'conn10'],
                hasError: false
            },
            {
                id: 'template3-dest1',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Valid Records',
                icon: '💾',
                description: 'Valid data destination',
                useCases: [],
                dataType: 'structured',
                position: { x: 600, y: 100 },
                inputs: ['conn9'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template3-dest2',
                type: 'destination',
                category: 'FlatFileDestination',
                name: 'Error Log',
                icon: '📄',
                description: 'Error records',
                useCases: [],
                dataType: 'text',
                position: { x: 600, y: 300 },
                inputs: ['conn10'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn8', source: 'template3-source', target: 'template3-split', isValid: true },
            { id: 'conn9', source: 'template3-split', target: 'template3-dest1', isValid: true },
            { id: 'conn10', source: 'template3-split', target: 'template3-dest2', isValid: true }
        ]
    },
    {
        id: 'union-all',
        name: 'Union Multiple Sources',
        description: 'Combine data from multiple similar sources into one output',
        difficulty: 'Beginner',
        components: [
            {
                id: 'template4-source1',
                type: 'source',
                category: 'FlatFileSource',
                name: 'January Data',
                icon: '📄',
                description: 'January CSV file',
                useCases: [],
                dataType: 'text',
                position: { x: 100, y: 100 },
                inputs: [],
                outputs: ['conn11'],
                hasError: false
            },
            {
                id: 'template4-source2',
                type: 'source',
                category: 'FlatFileSource',
                name: 'February Data',
                icon: '📄',
                description: 'February CSV file',
                useCases: [],
                dataType: 'text',
                position: { x: 100, y: 250 },
                inputs: [],
                outputs: ['conn12'],
                hasError: false
            },
            {
                id: 'template4-union',
                type: 'transformation',
                category: 'UnionAll',
                name: 'Union All',
                icon: '⊕',
                description: 'Combines multiple inputs into a single output.',
                useCases: ['Merging monthly files', 'Combining similar datasets'],
                dataType: 'text',
                position: { x: 400, y: 175 },
                inputs: ['conn11', 'conn12'],
                outputs: ['conn13'],
                hasError: false
            },
            {
                id: 'template4-dest',
                type: 'destination',
                category: 'FlatFileDestination',
                name: 'Combined Output',
                icon: '📄',
                description: 'All months combined',
                useCases: [],
                dataType: 'text',
                position: { x: 650, y: 175 },
                inputs: ['conn13'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn11', source: 'template4-source1', target: 'template4-union', isValid: true },
            { id: 'conn12', source: 'template4-source2', target: 'template4-union', isValid: true },
            { id: 'conn13', source: 'template4-union', target: 'template4-dest', isValid: true }
        ]
    },
    {
        id: 'lookup-enrichment',
        name: 'Lookup and Enrichment',
        description: 'Enrich data by looking up values from reference table',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template5-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Transaction Data',
                icon: '🗄️',
                description: 'Main transaction data',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 150 },
                inputs: [],
                outputs: ['conn14'],
                hasError: false
            },
            {
                id: 'template5-ref',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Customer Reference',
                icon: '🗄️',
                description: 'Customer details lookup table',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 300 },
                inputs: [],
                outputs: ['conn15'],
                hasError: false
            },
            {
                id: 'template5-lookup',
                type: 'transformation',
                category: 'Lookup',
                name: 'Lookup Customer',
                icon: '🔍',
                description: 'Joins data with a reference table.',
                useCases: ['Getting IDs from names', 'Validating codes'],
                dataType: 'structured',
                position: { x: 400, y: 150 },
                inputs: ['conn14', 'conn15'],
                outputs: ['conn16'],
                hasError: false,
                referenceInput: 'template5-ref'
            },
            {
                id: 'template5-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Enriched Data',
                icon: '💾',
                description: 'Data with customer details',
                useCases: [],
                dataType: 'structured',
                position: { x: 650, y: 150 },
                inputs: ['conn16'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn14', source: 'template5-source', target: 'template5-lookup', isValid: true },
            { id: 'conn15', source: 'template5-ref', target: 'template5-lookup', isValid: true },
            { id: 'conn16', source: 'template5-lookup', target: 'template5-dest', isValid: true }
        ]
    },
    {
        id: 'aggregation',
        name: 'Aggregation and Summary',
        description: 'Calculate totals, counts, and group by categories',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template6-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Sales Data',
                icon: '🗄️',
                description: 'Detailed sales transactions',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn17'],
                hasError: false
            },
            {
                id: 'template6-agg',
                type: 'transformation',
                category: 'Aggregate',
                name: 'Aggregate',
                icon: 'Σ',
                description: 'Aggregates values (Sum, Count, Avg) by group.',
                useCases: ['Daily totals', 'Counting records per category'],
                dataType: 'structured',
                position: { x: 400, y: 200 },
                inputs: ['conn17'],
                outputs: ['conn18'],
                hasError: false
            },
            {
                id: 'template6-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Summary Table',
                icon: '💾',
                description: 'Aggregated summary data',
                useCases: [],
                dataType: 'structured',
                position: { x: 650, y: 200 },
                inputs: ['conn18'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn17', source: 'template6-source', target: 'template6-agg', isValid: true },
            { id: 'conn18', source: 'template6-agg', target: 'template6-dest', isValid: true }
        ]
    },
    {
        id: 'multicast',
        name: 'Multicast to Multiple Destinations',
        description: 'Send same data to multiple destinations simultaneously',
        difficulty: 'Beginner',
        components: [
            {
                id: 'template7-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Customer Data',
                icon: '🗄️',
                description: 'Customer information',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn19'],
                hasError: false
            },
            {
                id: 'template7-multicast',
                type: 'transformation',
                category: 'Multicast',
                name: 'Multicast',
                icon: '📡',
                description: 'Distributes every input row to every output.',
                useCases: ['Sending data to multiple destinations', 'Logging while processing'],
                dataType: 'structured',
                position: { x: 350, y: 200 },
                inputs: ['conn19'],
                outputs: ['conn20', 'conn21', 'conn22'],
                hasError: false
            },
            {
                id: 'template7-dest1',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Production DB',
                icon: '💾',
                description: 'Main database',
                useCases: [],
                dataType: 'structured',
                position: { x: 600, y: 80 },
                inputs: ['conn20'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template7-dest2',
                type: 'destination',
                category: 'FlatFileDestination',
                name: 'Archive File',
                icon: '📄',
                description: 'Backup archive',
                useCases: [],
                dataType: 'text',
                position: { x: 600, y: 200 },
                inputs: ['conn21'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template7-dest3',
                type: 'destination',
                category: 'ExcelDestination',
                name: 'Report Excel',
                icon: '📗',
                description: 'Excel report',
                useCases: [],
                dataType: 'mixed',
                position: { x: 600, y: 320 },
                inputs: ['conn22'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn19', source: 'template7-source', target: 'template7-multicast', isValid: true },
            { id: 'conn20', source: 'template7-multicast', target: 'template7-dest1', isValid: true },
            { id: 'conn21', source: 'template7-multicast', target: 'template7-dest2', isValid: true },
            { id: 'conn22', source: 'template7-multicast', target: 'template7-dest3', isValid: true }
        ]
    },
    {
        id: 'derived-column',
        name: 'Data Transformation',
        description: 'Create calculated columns and transform data',
        difficulty: 'Beginner',
        components: [
            {
                id: 'template8-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Employee Data',
                icon: '🗄️',
                description: 'Employee information',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn23'],
                hasError: false
            },
            {
                id: 'template8-derived',
                type: 'transformation',
                category: 'DerivedColumn',
                name: 'Derived Column',
                icon: '➕',
                description: 'Creates new column values using expressions.',
                useCases: ['Concatenating names', 'Calculating totals', 'Cleaning strings'],
                dataType: 'structured',
                position: { x: 400, y: 200 },
                inputs: ['conn23'],
                outputs: ['conn24'],
                hasError: false
            },
            {
                id: 'template8-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Transformed Data',
                icon: '💾',
                description: 'Data with calculated columns',
                useCases: [],
                dataType: 'structured',
                position: { x: 700, y: 200 },
                inputs: ['conn24'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn23', source: 'template8-source', target: 'template8-derived', isValid: true },
            { id: 'conn24', source: 'template8-derived', target: 'template8-dest', isValid: true }
        ]
    },
    {
        id: 'json-to-db',
        name: 'JSON to Database',
        description: 'Import nested JSON data, flatten, and load to database',
        difficulty: 'Advanced',
        components: [
            {
                id: 'template9-source',
                type: 'source',
                category: 'JSONSource',
                name: 'API Response',
                icon: '{ }',
                description: 'JSON data from API',
                useCases: [],
                dataType: 'nested',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn25'],
                hasError: false
            },
            {
                id: 'template9-derived',
                type: 'transformation',
                category: 'DerivedColumn',
                name: 'Flatten JSON',
                icon: '➕',
                description: 'Flatten nested structures',
                useCases: [],
                dataType: 'structured',
                position: { x: 350, y: 200 },
                inputs: ['conn25'],
                outputs: ['conn26'],
                hasError: false
            },
            {
                id: 'template9-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Database Table',
                icon: '💾',
                description: 'Flattened data in DB',
                useCases: [],
                dataType: 'structured',
                position: { x: 600, y: 200 },
                inputs: ['conn26'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn25', source: 'template9-source', target: 'template9-derived', isValid: false },
            { id: 'conn26', source: 'template9-derived', target: 'template9-dest', isValid: true }
        ]
    },
    {
        id: 'row-count',
        name: 'Row Count and Auditing',
        description: 'Track the number of rows processed for auditing',
        difficulty: 'Beginner',
        components: [
            {
                id: 'template10-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Source Data',
                icon: '🗄️',
                description: 'Data to process',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn27'],
                hasError: false
            },
            {
                id: 'template10-rowcount',
                type: 'transformation',
                category: 'RowCount',
                name: 'Row Count',
                icon: '🔢',
                description: 'Counts rows passing through and stores in a variable.',
                useCases: ['Auditing', 'Logging process stats'],
                dataType: 'structured',
                position: { x: 400, y: 200 },
                inputs: ['conn27'],
                outputs: ['conn28'],
                hasError: false
            },
            {
                id: 'template10-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Destination',
                icon: '💾',
                description: 'Final destination',
                useCases: [],
                dataType: 'structured',
                position: { x: 700, y: 200 },
                inputs: ['conn28'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn27', source: 'template10-source', target: 'template10-rowcount', isValid: true },
            { id: 'conn28', source: 'template10-rowcount', target: 'template10-dest', isValid: true }
        ]
    },
    {
        id: 'scd-type2',
        name: 'Slowly Changing Dimension (SCD Type 2)',
        description: 'Track historical changes in dimension data with start/end dates',
        difficulty: 'Advanced',
        components: [
            {
                id: 'template11-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'New Customer Data',
                icon: '🗄️',
                description: 'Current customer snapshot',
                useCases: [],
                dataType: 'structured',
                position: { x: 50, y: 200 },
                inputs: [],
                outputs: ['conn29'],
                hasError: false
            },
            {
                id: 'template11-lookup',
                type: 'transformation',
                category: 'Lookup',
                name: 'Check Existing',
                icon: '🔍',
                description: 'Check if customer exists',
                useCases: [],
                dataType: 'structured',
                position: { x: 300, y: 200 },
                inputs: ['conn29', 'conn35'],
                outputs: ['conn30'],
                hasError: false,
                referenceInput: 'template11-ref'
            },
            {
                id: 'template11-ref',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Dimension Table',
                icon: '🗄️',
                description: 'Existing dimension data',
                useCases: [],
                dataType: 'structured',
                position: { x: 50, y: 350 },
                inputs: [],
                outputs: ['conn35'],
                hasError: false
            },
            {
                id: 'template11-split',
                type: 'transformation',
                category: 'ConditionalSplit',
                name: 'New vs Changed',
                icon: '🔀',
                description: 'Route new inserts and updates',
                useCases: [],
                dataType: 'structured',
                position: { x: 550, y: 200 },
                inputs: ['conn30'],
                outputs: ['conn31', 'conn32'],
                hasError: false
            },
            {
                id: 'template11-derived',
                type: 'transformation',
                category: 'DerivedColumn',
                name: 'Add Surrogate Key',
                icon: '➕',
                description: 'Generate surrogate keys and dates',
                useCases: [],
                dataType: 'structured',
                position: { x: 800, y: 150 },
                inputs: ['conn31'],
                outputs: ['conn33'],
                hasError: false
            },
            {
                id: 'template11-dest1',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Insert New Records',
                icon: '💾',
                description: 'New dimension entries',
                useCases: [],
                dataType: 'structured',
                position: { x: 1050, y: 150 },
                inputs: ['conn33'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template11-dest2',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Update Historical',
                icon: '💾',
                description: 'Close old records',
                useCases: [],
                dataType: 'structured',
                position: { x: 800, y: 280 },
                inputs: ['conn32'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn29', source: 'template11-source', target: 'template11-lookup', isValid: true },
            { id: 'conn35', source: 'template11-ref', target: 'template11-lookup', isValid: true },
            { id: 'conn30', source: 'template11-lookup', target: 'template11-split', isValid: true },
            { id: 'conn31', source: 'template11-split', target: 'template11-derived', isValid: true },
            { id: 'conn32', source: 'template11-split', target: 'template11-dest2', isValid: true },
            { id: 'conn33', source: 'template11-derived', target: 'template11-dest1', isValid: true }
        ]
    },
    {
        id: 'incremental-load',
        name: 'Incremental Data Load',
        description: 'Load only new or changed records since last run',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template12-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Source (WHERE ModifiedDate > ?)',
                icon: '🗄️',
                description: 'Query with date filter',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn36'],
                hasError: false
            },
            {
                id: 'template12-rowcount',
                type: 'transformation',
                category: 'RowCount',
                name: 'Count New Records',
                icon: '🔢',
                description: 'Track records processed',
                useCases: [],
                dataType: 'structured',
                position: { x: 400, y: 200 },
                inputs: ['conn36'],
                outputs: ['conn37'],
                hasError: false
            },
            {
                id: 'template12-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Staging Table',
                icon: '💾',
                description: 'Load to staging',
                useCases: [],
                dataType: 'structured',
                position: { x: 700, y: 200 },
                inputs: ['conn37'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn36', source: 'template12-source', target: 'template12-rowcount', isValid: true },
            { id: 'conn37', source: 'template12-rowcount', target: 'template12-dest', isValid: true }
        ]
    },
    {
        id: 'error-handling',
        name: 'Comprehensive Error Handling',
        description: 'Capture errors, redirect to error table, continue processing',
        difficulty: 'Advanced',
        components: [
            {
                id: 'template13-source',
                type: 'source',
                category: 'FlatFileSource',
                name: 'Raw Data File',
                icon: '📄',
                description: 'Potentially dirty data',
                useCases: [],
                dataType: 'text',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn38'],
                hasError: false
            },
            {
                id: 'template13-conv',
                type: 'transformation',
                category: 'DataConversion',
                name: 'Data Conversion',
                icon: '🔄',
                description: 'Convert with error redirection',
                useCases: [],
                dataType: 'structured',
                position: { x: 350, y: 200 },
                inputs: ['conn38'],
                outputs: ['conn39', 'conn40'],
                hasError: false
            },
            {
                id: 'template13-dest-valid',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Valid Data',
                icon: '💾',
                description: 'Successfully converted records',
                useCases: [],
                dataType: 'structured',
                position: { x: 600, y: 120 },
                inputs: ['conn39'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template13-derived',
                type: 'transformation',
                category: 'DerivedColumn',
                name: 'Add Error Info',
                icon: '➕',
                description: 'Add error codes and timestamps',
                useCases: [],
                dataType: 'text',
                position: { x: 600, y: 280 },
                inputs: ['conn40'],
                outputs: ['conn41'],
                hasError: false
            },
            {
                id: 'template13-dest-error',
                type: 'destination',
                category: 'FlatFileDestination',
                name: 'Error Log',
                icon: '📄',
                description: 'Failed conversion records',
                useCases: [],
                dataType: 'text',
                position: { x: 850, y: 280 },
                inputs: ['conn41'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn38', source: 'template13-source', target: 'template13-conv', isValid: false },
            { id: 'conn39', source: 'template13-conv', target: 'template13-dest-valid', isValid: true },
            { id: 'conn40', source: 'template13-conv', target: 'template13-derived', isValid: true },
            { id: 'conn41', source: 'template13-derived', target: 'template13-dest-error', isValid: true }
        ]
    },
    {
        id: 'data-quality',
        name: 'Data Quality Validation Pipeline',
        description: 'Validate data quality rules before loading',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template14-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Unvalidated Data',
                icon: '🗄️',
                description: 'Raw source data',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 250 },
                inputs: [],
                outputs: ['conn42'],
                hasError: false
            },
            {
                id: 'template14-split1',
                type: 'transformation',
                category: 'ConditionalSplit',
                name: 'Check Nulls',
                icon: '🔀',
                description: 'Filter null values',
                useCases: [],
                dataType: 'structured',
                position: { x: 300, y: 250 },
                inputs: ['conn42'],
                outputs: ['conn43', 'conn47'],
                hasError: false
            },
            {
                id: 'template14-split2',
                type: 'transformation',
                category: 'ConditionalSplit',
                name: 'Check Ranges',
                icon: '🔀',
                description: 'Validate value ranges',
                useCases: [],
                dataType: 'structured',
                position: { x: 500, y: 200 },
                inputs: ['conn43'],
                outputs: ['conn44', 'conn48'],
                hasError: false
            },
            {
                id: 'template14-split3',
                type: 'transformation',
                category: 'ConditionalSplit',
                name: 'Check Formats',
                icon: '🔀',
                description: 'Validate email, phone formats',
                useCases: [],
                dataType: 'structured',
                position: { x: 700, y: 150 },
                inputs: ['conn44'],
                outputs: ['conn45', 'conn49'],
                hasError: false
            },
            {
                id: 'template14-dest-valid',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Clean Data',
                icon: '💾',
                description: 'Passed all quality checks',
                useCases: [],
                dataType: 'structured',
                position: { x: 950, y: 150 },
                inputs: ['conn45'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template14-union',
                type: 'transformation',
                category: 'UnionAll',
                name: 'Combine Errors',
                icon: '⊕',
                description: 'All quality failures',
                useCases: [],
                dataType: 'structured',
                position: { x: 700, y: 350 },
                inputs: ['conn47', 'conn48', 'conn49'],
                outputs: ['conn46'],
                hasError: false
            },
            {
                id: 'template14-dest-error',
                type: 'destination',
                category: 'FlatFileDestination',
                name: 'Quality Failures',
                icon: '📄',
                description: 'Records that failed validation',
                useCases: [],
                dataType: 'text',
                position: { x: 950, y: 350 },
                inputs: ['conn46'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn42', source: 'template14-source', target: 'template14-split1', isValid: true },
            { id: 'conn43', source: 'template14-split1', target: 'template14-split2', isValid: true },
            { id: 'conn44', source: 'template14-split2', target: 'template14-split3', isValid: true },
            { id: 'conn45', source: 'template14-split3', target: 'template14-dest-valid', isValid: true },
            { id: 'conn47', source: 'template14-split1', target: 'template14-union', isValid: true },
            { id: 'conn48', source: 'template14-split2', target: 'template14-union', isValid: true },
            { id: 'conn49', source: 'template14-split3', target: 'template14-union', isValid: true },
            { id: 'conn46', source: 'template14-union', target: 'template14-dest-error', isValid: true }
        ]
    },
    {
        id: 'star-schema-load',
        name: 'Star Schema Fact Table Load',
        description: 'Look up dimension keys and load fact table',
        difficulty: 'Advanced',
        components: [
            {
                id: 'template15-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Fact Source',
                icon: '🗄️',
                description: 'Transaction data',
                useCases: [],
                dataType: 'structured',
                position: { x: 50, y: 250 },
                inputs: [],
                outputs: ['conn50'],
                hasError: false
            },
            {
                id: 'template15-lookup1',
                type: 'transformation',
                category: 'Lookup',
                name: 'Lookup Customer Key',
                icon: '🔍',
                description: 'Get customer dimension key',
                useCases: [],
                dataType: 'structured',
                position: { x: 300, y: 200 },
                inputs: ['conn50', 'conn54'],
                outputs: ['conn51'],
                hasError: false,
                referenceInput: 'template15-dim1'
            },
            {
                id: 'template15-dim1',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Customer Dimension',
                icon: '🗄️',
                description: 'Customer keys',
                useCases: [],
                dataType: 'structured',
                position: { x: 50, y: 100 },
                inputs: [],
                outputs: ['conn54'],
                hasError: false
            },
            {
                id: 'template15-lookup2',
                type: 'transformation',
                category: 'Lookup',
                name: 'Lookup Product Key',
                icon: '🔍',
                description: 'Get product dimension key',
                useCases: [],
                dataType: 'structured',
                position: { x: 550, y: 200 },
                inputs: ['conn51', 'conn55'],
                outputs: ['conn52'],
                hasError: false,
                referenceInput: 'template15-dim2'
            },
            {
                id: 'template15-dim2',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Product Dimension',
                icon: '🗄️',
                description: 'Product keys',
                useCases: [],
                dataType: 'structured',
                position: { x: 300, y: 100 },
                inputs: [],
                outputs: ['conn55'],
                hasError: false
            },
            {
                id: 'template15-lookup3',
                type: 'transformation',
                category: 'Lookup',
                name: 'Lookup Date Key',
                icon: '🔍',
                description: 'Get date dimension key',
                useCases: [],
                dataType: 'structured',
                position: { x: 800, y: 200 },
                inputs: ['conn52', 'conn56'],
                outputs: ['conn53'],
                hasError: false,
                referenceInput: 'template15-dim3'
            },
            {
                id: 'template15-dim3',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Date Dimension',
                icon: '🗄️',
                description: 'Date keys',
                useCases: [],
                dataType: 'structured',
                position: { x: 550, y: 100 },
                inputs: [],
                outputs: ['conn56'],
                hasError: false
            },
            {
                id: 'template15-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Fact Table',
                icon: '💾',
                description: 'Final fact table',
                useCases: [],
                dataType: 'structured',
                position: { x: 1050, y: 200 },
                inputs: ['conn53'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn50', source: 'template15-source', target: 'template15-lookup1', isValid: true },
            { id: 'conn54', source: 'template15-dim1', target: 'template15-lookup1', isValid: true },
            { id: 'conn51', source: 'template15-lookup1', target: 'template15-lookup2', isValid: true },
            { id: 'conn55', source: 'template15-dim2', target: 'template15-lookup2', isValid: true },
            { id: 'conn52', source: 'template15-lookup2', target: 'template15-lookup3', isValid: true },
            { id: 'conn56', source: 'template15-dim3', target: 'template15-lookup3', isValid: true },
            { id: 'conn53', source: 'template15-lookup3', target: 'template15-dest', isValid: true }
        ]
    },
    {
        id: 'deduplication',
        name: 'Data Deduplication',
        description: 'Remove duplicate records based on business key',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template16-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Data with Duplicates',
                icon: '🗄️',
                description: 'Undeduped source',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn57'],
                hasError: false
            },
            {
                id: 'template16-sort',
                type: 'transformation',
                category: 'Sort',
                name: 'Sort by Key + Date',
                icon: '⬆️',
                description: 'Order by business key',
                useCases: [],
                dataType: 'structured',
                position: { x: 350, y: 200 },
                inputs: ['conn57'],
                outputs: ['conn58'],
                hasError: false,
                isSorted: true
            },
            {
                id: 'template16-agg',
                type: 'transformation',
                category: 'Aggregate',
                name: 'Group by Key (Keep Latest)',
                icon: 'Σ',
                description: 'Deduplicate aggregation',
                useCases: [],
                dataType: 'structured',
                position: { x: 600, y: 200 },
                inputs: ['conn58'],
                outputs: ['conn59'],
                hasError: false
            },
            {
                id: 'template16-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Unique Records',
                icon: '💾',
                description: 'Deduplicated data',
                useCases: [],
                dataType: 'structured',
                position: { x: 850, y: 200 },
                inputs: ['conn59'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn57', source: 'template16-source', target: 'template16-sort', isValid: true },
            { id: 'conn58', source: 'template16-sort', target: 'template16-agg', isValid: true },
            { id: 'conn59', source: 'template16-agg', target: 'template16-dest', isValid: true }
        ]
    },
    {
        id: 'xml-parsing',
        name: 'XML Data Extraction',
        description: 'Parse XML files and extract into relational tables',
        difficulty: 'Advanced',
        components: [
            {
                id: 'template17-source',
                type: 'source',
                category: 'XMLSource',
                name: 'XML File',
                icon: '🏷️',
                description: 'Complex XML document',
                useCases: [],
                dataType: 'nested',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn60'],
                hasError: false
            },
            {
                id: 'template17-derived',
                type: 'transformation',
                category: 'DerivedColumn',
                name: 'Parse XML Nodes',
                icon: '➕',
                description: 'Extract nested elements',
                useCases: [],
                dataType: 'structured',
                position: { x: 350, y: 200 },
                inputs: ['conn60'],
                outputs: ['conn61'],
                hasError: false
            },
            {
                id: 'template17-multicast',
                type: 'transformation',
                category: 'Multicast',
                name: 'Split to Tables',
                icon: '📡',
                description: 'Send to multiple normalized tables',
                useCases: [],
                dataType: 'structured',
                position: { x: 600, y: 200 },
                inputs: ['conn61'],
                outputs: ['conn62', 'conn63', 'conn64'],
                hasError: false
            },
            {
                id: 'template17-dest1',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Header Table',
                icon: '💾',
                description: 'Parent records',
                useCases: [],
                dataType: 'structured',
                position: { x: 850, y: 80 },
                inputs: ['conn62'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template17-dest2',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Line Items Table',
                icon: '💾',
                description: 'Child records',
                useCases: [],
                dataType: 'structured',
                position: { x: 850, y: 200 },
                inputs: ['conn63'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template17-dest3',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Attributes Table',
                icon: '💾',
                description: 'Detail records',
                useCases: [],
                dataType: 'structured',
                position: { x: 850, y: 320 },
                inputs: ['conn64'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn60', source: 'template17-source', target: 'template17-derived', isValid: false },
            { id: 'conn61', source: 'template17-derived', target: 'template17-multicast', isValid: true },
            { id: 'conn62', source: 'template17-multicast', target: 'template17-dest1', isValid: true },
            { id: 'conn63', source: 'template17-multicast', target: 'template17-dest2', isValid: true },
            { id: 'conn64', source: 'template17-multicast', target: 'template17-dest3', isValid: true }
        ]
    },
    {
        id: 'excel-consolidation',
        name: 'Multiple Excel Files Consolidation',
        description: 'Combine multiple Excel sheets from different workbooks',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template18-source1',
                type: 'source',
                category: 'ExcelSource',
                name: 'Q1 Report',
                icon: '📗',
                description: 'First quarter Excel',
                useCases: [],
                dataType: 'mixed',
                position: { x: 50, y: 100 },
                inputs: [],
                outputs: ['conn65'],
                hasError: false
            },
            {
                id: 'template18-conv1',
                type: 'transformation',
                category: 'DataConversion',
                name: 'Standardize Q1',
                icon: '🔄',
                description: 'Fix Excel types',
                useCases: [],
                dataType: 'structured',
                position: { x: 250, y: 100 },
                inputs: ['conn65'],
                outputs: ['conn69'],
                hasError: false
            },
            {
                id: 'template18-source2',
                type: 'source',
                category: 'ExcelSource',
                name: 'Q2 Report',
                icon: '📗',
                description: 'Second quarter Excel',
                useCases: [],
                dataType: 'mixed',
                position: { x: 50, y: 220 },
                inputs: [],
                outputs: ['conn66'],
                hasError: false
            },
            {
                id: 'template18-conv2',
                type: 'transformation',
                category: 'DataConversion',
                name: 'Standardize Q2',
                icon: '🔄',
                description: 'Fix Excel types',
                useCases: [],
                dataType: 'structured',
                position: { x: 250, y: 220 },
                inputs: ['conn66'],
                outputs: ['conn70'],
                hasError: false
            },
            {
                id: 'template18-source3',
                type: 'source',
                category: 'ExcelSource',
                name: 'Q3 Report',
                icon: '📗',
                description: 'Third quarter Excel',
                useCases: [],
                dataType: 'mixed',
                position: { x: 50, y: 340 },
                inputs: [],
                outputs: ['conn67'],
                hasError: false
            },
            {
                id: 'template18-conv3',
                type: 'transformation',
                category: 'DataConversion',
                name: 'Standardize Q3',
                icon: '🔄',
                description: 'Fix Excel types',
                useCases: [],
                dataType: 'structured',
                position: { x: 250, y: 340 },
                inputs: ['conn67'],
                outputs: ['conn71'],
                hasError: false
            },
            {
                id: 'template18-union',
                type: 'transformation',
                category: 'UnionAll',
                name: 'Combine Quarters',
                icon: '⊕',
                description: 'Union all quarters',
                useCases: [],
                dataType: 'structured',
                position: { x: 500, y: 220 },
                inputs: ['conn69', 'conn70', 'conn71'],
                outputs: ['conn68'],
                hasError: false
            },
            {
                id: 'template18-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Annual Summary',
                icon: '💾',
                description: 'Consolidated yearly data',
                useCases: [],
                dataType: 'structured',
                position: { x: 750, y: 220 },
                inputs: ['conn68'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn65', source: 'template18-source1', target: 'template18-conv1', isValid: false },
            { id: 'conn66', source: 'template18-source2', target: 'template18-conv2', isValid: false },
            { id: 'conn67', source: 'template18-source3', target: 'template18-conv3', isValid: false },
            { id: 'conn69', source: 'template18-conv1', target: 'template18-union', isValid: true },
            { id: 'conn70', source: 'template18-conv2', target: 'template18-union', isValid: true },
            { id: 'conn71', source: 'template18-conv3', target: 'template18-union', isValid: true },
            { id: 'conn68', source: 'template18-union', target: 'template18-dest', isValid: true }
        ]
    },
    {
        id: 'audit-trail',
        name: 'Data Audit Trail Pattern',
        description: 'Track who, what, when for data changes with logging',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template19-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Source Data',
                icon: '🗄️',
                description: 'Data to audit',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn72'],
                hasError: false
            },
            {
                id: 'template19-derived',
                type: 'transformation',
                category: 'DerivedColumn',
                name: 'Add Audit Columns',
                icon: '➕',
                description: 'CreatedBy, CreatedDate, ModifiedBy, etc',
                useCases: [],
                dataType: 'structured',
                position: { x: 350, y: 200 },
                inputs: ['conn72'],
                outputs: ['conn73'],
                hasError: false
            },
            {
                id: 'template19-rowcount',
                type: 'transformation',
                category: 'RowCount',
                name: 'Count Records',
                icon: '🔢',
                description: 'Track processing count',
                useCases: [],
                dataType: 'structured',
                position: { x: 600, y: 200 },
                inputs: ['conn73'],
                outputs: ['conn74'],
                hasError: false
            },
            {
                id: 'template19-multicast',
                type: 'transformation',
                category: 'Multicast',
                name: 'Split for Audit',
                icon: '📡',
                description: 'Send to data + audit log',
                useCases: [],
                dataType: 'structured',
                position: { x: 850, y: 200 },
                inputs: ['conn74'],
                outputs: ['conn75', 'conn76'],
                hasError: false
            },
            {
                id: 'template19-dest-data',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Main Table',
                icon: '💾',
                description: 'Business data',
                useCases: [],
                dataType: 'structured',
                position: { x: 1100, y: 130 },
                inputs: ['conn75'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template19-dest-audit',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Audit Log Table',
                icon: '💾',
                description: 'Change tracking',
                useCases: [],
                dataType: 'structured',
                position: { x: 1100, y: 270 },
                inputs: ['conn76'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn72', source: 'template19-source', target: 'template19-derived', isValid: true },
            { id: 'conn73', source: 'template19-derived', target: 'template19-rowcount', isValid: true },
            { id: 'conn74', source: 'template19-rowcount', target: 'template19-multicast', isValid: true },
            { id: 'conn75', source: 'template19-multicast', target: 'template19-dest-data', isValid: true },
            { id: 'conn76', source: 'template19-multicast', target: 'template19-dest-audit', isValid: true }
        ]
    },
    {
        id: 'full-etl-pipeline',
        name: 'Complete ETL Pipeline (Extract-Transform-Load)',
        description: 'Full end-to-end ETL with staging, transformation, and warehouse load',
        difficulty: 'Advanced',
        components: [
            {
                id: 'template20-source1',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Orders Source',
                icon: '🗄️',
                description: 'OLTP orders table',
                useCases: [],
                dataType: 'structured',
                position: { x: 50, y: 150 },
                inputs: [],
                outputs: ['conn77'],
                hasError: false
            },
            {
                id: 'template20-source2',
                type: 'source',
                category: 'FlatFileSource',
                name: 'Customer CSV',
                icon: '📄',
                description: 'Customer master data',
                useCases: [],
                dataType: 'text',
                position: { x: 50, y: 300 },
                inputs: [],
                outputs: ['conn78'],
                hasError: false
            },
            {
                id: 'template20-conv',
                type: 'transformation',
                category: 'DataConversion',
                name: 'Standardize Types',
                icon: '🔄',
                description: 'Convert CSV to typed data',
                useCases: [],
                dataType: 'structured',
                position: { x: 250, y: 300 },
                inputs: ['conn78'],
                outputs: ['conn84'],
                hasError: false
            },
            {
                id: 'template20-sort1',
                type: 'transformation',
                category: 'Sort',
                name: 'Sort Orders',
                icon: '⬆️',
                description: 'Sort by customer key',
                useCases: [],
                dataType: 'structured',
                position: { x: 250, y: 150 },
                inputs: ['conn77'],
                outputs: ['conn82'],
                hasError: false,
                isSorted: true
            },
            {
                id: 'template20-sort2',
                type: 'transformation',
                category: 'Sort',
                name: 'Sort Customers',
                icon: '⬆️',
                description: 'Sort by customer key',
                useCases: [],
                dataType: 'structured',
                position: { x: 450, y: 300 },
                inputs: ['conn84'],
                outputs: ['conn83'],
                hasError: false,
                isSorted: true
            },
            {
                id: 'template20-merge',
                type: 'transformation',
                category: 'MergeJoin',
                name: 'Join Orders & Customers',
                icon: '🔗',
                description: 'Enrich orders with customer data',
                useCases: [],
                dataType: 'structured',
                position: { x: 650, y: 225 },
                inputs: ['conn82', 'conn83'],
                outputs: ['conn79'],
                hasError: false
            },
            {
                id: 'template20-derived',
                type: 'transformation',
                category: 'DerivedColumn',
                name: 'Calculate Metrics',
                icon: '➕',
                description: 'Total amount, margin, etc',
                useCases: [],
                dataType: 'structured',
                position: { x: 900, y: 225 },
                inputs: ['conn79'],
                outputs: ['conn80'],
                hasError: false
            },
            {
                id: 'template20-agg',
                type: 'transformation',
                category: 'Aggregate',
                name: 'Daily Summary',
                icon: 'Σ',
                description: 'Aggregate by date',
                useCases: [],
                dataType: 'structured',
                position: { x: 1100, y: 225 },
                inputs: ['conn80'],
                outputs: ['conn81'],
                hasError: false
            },
            {
                id: 'template20-dest',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Data Warehouse',
                icon: '💾',
                description: 'Final warehouse fact table',
                useCases: [],
                dataType: 'structured',
                position: { x: 1300, y: 225 },
                inputs: ['conn81'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn77', source: 'template20-source1', target: 'template20-sort1', isValid: true },
            { id: 'conn78', source: 'template20-source2', target: 'template20-conv', isValid: false },
            { id: 'conn84', source: 'template20-conv', target: 'template20-sort2', isValid: true },
            { id: 'conn82', source: 'template20-sort1', target: 'template20-merge', isValid: true },
            { id: 'conn83', source: 'template20-sort2', target: 'template20-merge', isValid: true },
            { id: 'conn79', source: 'template20-merge', target: 'template20-derived', isValid: true },
            { id: 'conn80', source: 'template20-derived', target: 'template20-agg', isValid: true },
            { id: 'conn81', source: 'template20-agg', target: 'template20-dest', isValid: true }
        ]
    },
    {
        id: 'sql-to-excel-method1',
        name: 'SQL to Multi-Sheet Excel (Method 1: Conditional Split)',
        description: 'Split SQL data into Active/Termed employees using Conditional Split - RECOMMENDED',
        difficulty: 'Beginner',
        components: [
            {
                id: 'template21-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Employee Table (SQL)',
                icon: '🗄️',
                description: 'SELECT * FROM Employees',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn85'],
                hasError: false
            },
            {
                id: 'template21-split',
                type: 'transformation',
                category: 'ConditionalSplit',
                name: 'Split: Active vs Termed',
                icon: '🔀',
                description: 'Condition: EmploymentStatus == "Active"',
                useCases: [],
                dataType: 'structured',
                position: { x: 400, y: 200 },
                inputs: ['conn85'],
                outputs: ['conn86', 'conn87'],
                hasError: false
            },
            {
                id: 'template21-dest1',
                type: 'destination',
                category: 'ExcelDestination',
                name: 'Sheet1: Active Employees',
                icon: '📗',
                description: 'Output to ActiveEmployees sheet',
                useCases: [],
                dataType: 'mixed',
                position: { x: 700, y: 100 },
                inputs: ['conn86'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template21-dest2',
                type: 'destination',
                category: 'ExcelDestination',
                name: 'Sheet2: Termed Employees',
                icon: '📗',
                description: 'Output to TermedEmployees sheet',
                useCases: [],
                dataType: 'mixed',
                position: { x: 700, y: 300 },
                inputs: ['conn87'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn85', source: 'template21-source', target: 'template21-split', isValid: true },
            { id: 'conn86', source: 'template21-split', target: 'template21-dest1', isValid: true },
            { id: 'conn87', source: 'template21-split', target: 'template21-dest2', isValid: true }
        ]
    },
    {
        id: 'sql-to-excel-method2',
        name: 'SQL to Multi-Sheet Excel (Method 2: Separate Queries)',
        description: 'Use two SQL queries with WHERE clauses - BETTER FOR PERFORMANCE',
        difficulty: 'Beginner',
        components: [
            {
                id: 'template22-source1',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Active Employees Query',
                icon: '🗄️',
                description: 'SELECT * FROM Employees WHERE Status = \'Active\'',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 100 },
                inputs: [],
                outputs: ['conn88'],
                hasError: false
            },
            {
                id: 'template22-source2',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Termed Employees Query',
                icon: '🗄️',
                description: 'SELECT * FROM Employees WHERE Status = \'Termed\'',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 300 },
                inputs: [],
                outputs: ['conn89'],
                hasError: false
            },
            {
                id: 'template22-dest1',
                type: 'destination',
                category: 'ExcelDestination',
                name: 'Sheet1: Active Employees',
                icon: '📗',
                description: 'Output to ActiveEmployees sheet',
                useCases: [],
                dataType: 'mixed',
                position: { x: 450, y: 100 },
                inputs: ['conn88'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template22-dest2',
                type: 'destination',
                category: 'ExcelDestination',
                name: 'Sheet2: Termed Employees',
                icon: '📗',
                description: 'Output to TermedEmployees sheet',
                useCases: [],
                dataType: 'mixed',
                position: { x: 450, y: 300 },
                inputs: ['conn89'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn88', source: 'template22-source1', target: 'template22-dest1', isValid: true },
            { id: 'conn89', source: 'template22-source2', target: 'template22-dest2', isValid: true }
        ]
    },
    {
        id: 'sql-to-excel-method3',
        name: 'SQL to Multi-Sheet Excel (Method 3: Multicast)',
        description: 'Use Multicast then Conditional Split - FLEXIBLE FOR ADDITIONAL PROCESSING',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template23-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'Employee Table (SQL)',
                icon: '🗄️',
                description: 'SELECT * FROM Employees',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn90'],
                hasError: false
            },
            {
                id: 'template23-multicast',
                type: 'transformation',
                category: 'Multicast',
                name: 'Broadcast Data',
                icon: '📡',
                description: 'Send to both processing paths',
                useCases: [],
                dataType: 'structured',
                position: { x: 350, y: 200 },
                inputs: ['conn90'],
                outputs: ['conn91', 'conn92'],
                hasError: false
            },
            {
                id: 'template23-split1',
                type: 'transformation',
                category: 'ConditionalSplit',
                name: 'Filter Active Only',
                icon: '🔀',
                description: 'Keep Status == "Active"',
                useCases: [],
                dataType: 'structured',
                position: { x: 600, y: 100 },
                inputs: ['conn91'],
                outputs: ['conn93'],
                hasError: false
            },
            {
                id: 'template23-split2',
                type: 'transformation',
                category: 'ConditionalSplit',
                name: 'Filter Termed Only',
                icon: '🔀',
                description: 'Keep Status == "Termed"',
                useCases: [],
                dataType: 'structured',
                position: { x: 600, y: 300 },
                inputs: ['conn92'],
                outputs: ['conn94'],
                hasError: false
            },
            {
                id: 'template23-dest1',
                type: 'destination',
                category: 'ExcelDestination',
                name: 'Sheet1: Active Employees',
                icon: '📗',
                description: 'Output to ActiveEmployees sheet',
                useCases: [],
                dataType: 'mixed',
                position: { x: 850, y: 100 },
                inputs: ['conn93'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template23-dest2',
                type: 'destination',
                category: 'ExcelDestination',
                name: 'Sheet2: Termed Employees',
                icon: '📗',
                description: 'Output to TermedEmployees sheet',
                useCases: [],
                dataType: 'mixed',
                position: { x: 850, y: 300 },
                inputs: ['conn94'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn90', source: 'template23-source', target: 'template23-multicast', isValid: true },
            { id: 'conn91', source: 'template23-multicast', target: 'template23-split1', isValid: true },
            { id: 'conn92', source: 'template23-multicast', target: 'template23-split2', isValid: true },
            { id: 'conn93', source: 'template23-split1', target: 'template23-dest1', isValid: true },
            { id: 'conn94', source: 'template23-split2', target: 'template23-dest2', isValid: true }
        ]
    },
    {
        id: 'stored-proc-execution',
        name: 'Execute Stored Procedure with Parameters',
        description: 'Call SP, process results, handle output parameters',
        difficulty: 'Intermediate',
        components: [
            {
                id: 'template24-source',
                type: 'source',
                category: 'OLEDBSource',
                name: 'EXEC sp_GetEmployees @Date',
                icon: '🗄️',
                description: 'Execute stored procedure with parameter',
                useCases: [],
                dataType: 'structured',
                position: { x: 100, y: 200 },
                inputs: [],
                outputs: ['conn95'],
                hasError: false
            },
            {
                id: 'template24-derived',
                type: 'transformation',
                category: 'DerivedColumn',
                name: 'Add Processing Metadata',
                icon: '➕',
                description: 'Add LoadDate, BatchID columns',
                useCases: [],
                dataType: 'structured',
                position: { x: 400, y: 200 },
                inputs: ['conn95'],
                outputs: ['conn96'],
                hasError: false
            },
            {
                id: 'template24-split',
                type: 'transformation',
                category: 'ConditionalSplit',
                name: 'Validate Data Quality',
                icon: '🔀',
                description: 'Separate valid vs invalid records',
                useCases: [],
                dataType: 'structured',
                position: { x: 650, y: 200 },
                inputs: ['conn96'],
                outputs: ['conn97', 'conn98'],
                hasError: false
            },
            {
                id: 'template24-dest-valid',
                type: 'destination',
                category: 'OLEDBDestination',
                name: 'Target Table',
                icon: '💾',
                description: 'Load valid records',
                useCases: [],
                dataType: 'structured',
                position: { x: 900, y: 130 },
                inputs: ['conn97'],
                outputs: [],
                hasError: false
            },
            {
                id: 'template24-dest-error',
                type: 'destination',
                category: 'FlatFileDestination',
                name: 'Error Log',
                icon: '📄',
                description: 'Log invalid records',
                useCases: [],
                dataType: 'text',
                position: { x: 900, y: 270 },
                inputs: ['conn98'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn95', source: 'template24-source', target: 'template24-derived', isValid: true },
            { id: 'conn96', source: 'template24-derived', target: 'template24-split', isValid: true },
            { id: 'conn97', source: 'template24-split', target: 'template24-dest-valid', isValid: true },
            { id: 'conn98', source: 'template24-split', target: 'template24-dest-error', isValid: true }
        ]
    },
    {
        id: 'multi-sp-pattern',
        name: 'Multiple Stored Procedures Pattern',
        description: 'Execute multiple SPs in parallel, combine results',
        difficulty: 'Advanced',
        components: [
            {
                id: 'template25-sp1',
                type: 'source',
                category: 'OLEDBSource',
                name: 'EXEC sp_GetDepartments',
                icon: '🗄️',
                description: 'Get department data',
                useCases: [],
                dataType: 'structured',
                position: { x: 50, y: 100 },
                inputs: [],
                outputs: ['conn99'],
                hasError: false
            },
            {
                id: 'template25-sp2',
                type: 'source',
                category: 'OLEDBSource',
                name: 'EXEC sp_GetEmployees',
                icon: '🗄️',
                description: 'Get employee data',
                useCases: [],
                dataType: 'structured',
                position: { x: 50, y: 250 },
                inputs: [],
                outputs: ['conn100'],
                hasError: false
            },
            {
                id: 'template25-sp3',
                type: 'source',
                category: 'OLEDBSource',
                name: 'EXEC sp_GetSalaries',
                icon: '🗄️',
                description: 'Get salary data',
                useCases: [],
                dataType: 'structured',
                position: { x: 50, y: 400 },
                inputs: [],
                outputs: ['conn101'],
                hasError: false
            },
            {
                id: 'template25-sort1',
                type: 'transformation',
                category: 'Sort',
                name: 'Sort Departments',
                icon: '⬆️',
                description: 'Sort by DeptID',
                useCases: [],
                dataType: 'structured',
                position: { x: 300, y: 100 },
                inputs: ['conn99'],
                outputs: ['conn105'],
                hasError: false,
                isSorted: true
            },
            {
                id: 'template25-sort2',
                type: 'transformation',
                category: 'Sort',
                name: 'Sort Employees',
                icon: '⬆️',
                description: 'Sort by EmpID, DeptID',
                useCases: [],
                dataType: 'structured',
                position: { x: 300, y: 250 },
                inputs: ['conn100'],
                outputs: ['conn106'],
                hasError: false,
                isSorted: true
            },
            {
                id: 'template25-merge1',
                type: 'transformation',
                category: 'MergeJoin',
                name: 'Join Emp + Dept',
                icon: '🔗',
                description: 'LEFT JOIN on DeptID',
                useCases: [],
                dataType: 'structured',
                position: { x: 550, y: 175 },
                inputs: ['conn106', 'conn105'],
                outputs: ['conn102'],
                hasError: false
            },
            {
                id: 'template25-sort3',
                type: 'transformation',
                category: 'Sort',
                name: 'Sort for Salary Join',
                icon: '⬆️',
                description: 'Sort by EmpID',
                useCases: [],
                dataType: 'structured',
                position: { x: 800, y: 175 },
                inputs: ['conn102'],
                outputs: ['conn107'],
                hasError: false,
                isSorted: true
            },
            {
                id: 'template25-sort4',
                type: 'transformation',
                category: 'Sort',
                name: 'Sort Salaries',
                icon: '⬆️',
                description: 'Sort by EmpID',
                useCases: [],
                dataType: 'structured',
                position: { x: 300, y: 400 },
                inputs: ['conn101'],
                outputs: ['conn108'],
                hasError: false,
                isSorted: true
            },
            {
                id: 'template25-merge2',
                type: 'transformation',
                category: 'MergeJoin',
                name: 'Join with Salaries',
                icon: '🔗',
                description: 'INNER JOIN on EmpID',
                useCases: [],
                dataType: 'structured',
                position: { x: 1050, y: 287 },
                inputs: ['conn107', 'conn108'],
                outputs: ['conn103'],
                hasError: false
            },
            {
                id: 'template25-derived',
                type: 'transformation',
                category: 'DerivedColumn',
                name: 'Calculate Total Comp',
                icon: '➕',
                description: 'Salary + Bonus + Benefits',
                useCases: [],
                dataType: 'structured',
                position: { x: 1300, y: 287 },
                inputs: ['conn103'],
                outputs: ['conn104'],
                hasError: false
            },
            {
                id: 'template25-dest',
                type: 'destination',
                category: 'ExcelDestination',
                name: 'Employee Summary Report',
                icon: '📗',
                description: 'Final consolidated report',
                useCases: [],
                dataType: 'mixed',
                position: { x: 1550, y: 287 },
                inputs: ['conn104'],
                outputs: [],
                hasError: false
            }
        ],
        connections: [
            { id: 'conn99', source: 'template25-sp1', target: 'template25-sort1', isValid: true },
            { id: 'conn100', source: 'template25-sp2', target: 'template25-sort2', isValid: true },
            { id: 'conn101', source: 'template25-sp3', target: 'template25-sort4', isValid: true },
            { id: 'conn105', source: 'template25-sort1', target: 'template25-merge1', isValid: true },
            { id: 'conn106', source: 'template25-sort2', target: 'template25-merge1', isValid: true },
            { id: 'conn102', source: 'template25-merge1', target: 'template25-sort3', isValid: true },
            { id: 'conn107', source: 'template25-sort3', target: 'template25-merge2', isValid: true },
            { id: 'conn108', source: 'template25-sort4', target: 'template25-merge2', isValid: true },
            { id: 'conn103', source: 'template25-merge2', target: 'template25-derived', isValid: true },
            { id: 'conn104', source: 'template25-derived', target: 'template25-dest', isValid: true }
        ]
    }
];
